description: >
  Because these scripts use bash-specific features, Bash is required. Bash is the default shell used on CircleCI and the Orb will be compatible with most images.
  If using an Alpine base image, you will need to call apk add bash before calling this Orb, or create a derivative base image that calls RUN apk add bash.
  If Bash is not available, an error message will be logged and the task will fail.

docker:
  - image: cimg/base:2022.09
    environment:
      TERM: dumb
resource_class: small
